# -*- coding: utf-8 -*-
"""Chapter5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18jFwIBnFS75RQbAaPvkmIw9wLqkwZG_C
"""

# Commented out IPython magic to ensure Python compatibility.
# 리스트 5-1-(1)
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline


# 데이터 생성 --------------------------------
np.random.seed(seed=1) # 난수를 고정
X_min = 4 # X의 하한(표시 용)
X_max = 30 # X의 상한(표시 용)
X_n = 16 # X의 상한(표시 용)
X = 5 + 25 * np.random.rand(X_n)
# np.random.rand(X_n) --> [0,1] @ 100%
#  25 * [0,1] @ 100%  --> [0,25] @ 100%
#  5 + [0,25] @ 100% --> [5,30] @ 100%
# 따라서 X는 5에서 30세에 100% 가 나타나는 분포

Prm_c = [170, 108, 0.2] # 생성 매개 변수
T = Prm_c[0] - Prm_c[1] * np.exp(-Prm_c[2] * X) \
+ 4 * np.random.randn(X_n) # (A)

# Prm_c[1] * np.exp(-Prm_c[2] * X) 이 부분이 170 cm 에서
# X: [5,30] @ 100%
# Prm_c[2] * X :  0.2 * [5,30] @ 100% = [1,6] @ 100%
# -Prm_c[2] * X :  -1* [1,6] @ 100% = [-6,-1]@ 100%
# np.exp(-Prm_c[2] * X) : [0.0025,0.3679]@ 100%
# Prm_c[1] * np.exp(-Prm_c[2] * X) = 108 * [0.0025,0.3679]@ 100%
  # 108*np.exp(-6) = 0.268
  # 108*np.exp(-1) = 39.731
# Prm_c[1] * np.exp(-Prm_c[2] * X) :  [0.268, 39.731]@ 100%
# Prm_c[0] - Prm_c[1] * np.exp(-Prm_c[2] * X) = 170-[0.268, 39.731]@ 100%
  # 170-108*np.exp(-6) = 169.73
  # 170-108*np.exp(-1) = 130.269
  # Prm_c[0] - Prm_c[1] * np.exp(-Prm_c[2] * X) : [130.269, 169.73]@ 100%

#  4 * np.random.randn(X_n) : 4*[-1, 1] @ 68% =[-4, 4] @ 68%
#  Prm_c[0] - Prm_c[1] * np.exp(-Prm_c[2] * X) + 4 * np.random.randn(X_n)
#  [130.269, 169.73]@ 100% + [-4, 4] @ 68%
#  [126.269, 173.73]@ 68%

#Prm_c[2] * X
# array([3.08652401, 3.79344914, 1.70193469, 1.99050745, 5.00372284,
#        5.84130788, 2.56712089, 4.46161308, 5.38194576, 5.47303332,
#        1.42522106, 1.19527392, 1.8491521 , 5.39071252, 1.49173417,
#        3.10553813])
# np.exp(-Prm_c[2] * X)
# array([0.04566039, 0.0225178 , 0.18233043, 0.13662608, 0.00671291,
#       0.00290504, 0.07675622, 0.01154373, 0.00459886, 0.00419848,
#       0.2404553 , 0.30262105, 0.15737054, 0.00455872, 0.22498216,
#       0.0448004 ])
#np.exp(-1)
#np.exp(-6)
#Prm_c[1]
# 108
#np.exp(-6)*108
# 0.26770523507996674
#np.exp(-12)*108
# 0.0006635749341594466
#np.exp(-1)*108
#39.73097964651577
#Prm_c[0] - Prm_c[1] * np.exp(-Prm_c[2] * X)
#array([165.06867746, 167.56807753, 150.30831365, 155.24438362,
#       169.27500579, 169.6862556 , 161.71032855, 168.75327745,
#       169.50332259, 169.54656443, 144.03082727, 137.3169266 ,
#       153.00398118, 169.50765781, 145.70192673, 165.16155638])
#Prm_c[0] -  np.exp(-6)*108
#169.73229476492003
#Prm_c[0] -  np.exp(-1)*108
# 130.26902035348422
# [130, 169]@100%
# 4 * np.random.randn(X_n)
# array([-2.68498452, -0.0506584 , -4.46924139,  0.93766279,  6.63920871,
#         2.96817664, -0.76734221, -3.55051586, -2.98863318,  6.7698184 ,
#         0.20323102, -2.54798259,  0.76366194,  8.40102055,  0.48063581,
#        2.46881244])
# [-4, 4]@68%

# [130, 169]@100% + [-4, 4]@68%
# [126, 173]@68%


np.savez('ch5_data.npz', X=X, X_min=X_min, X_max=X_max, X_n=X_n, T=T) # (B)

# 리스트 5-1-(2)
print(X)

# 리스트 5-1-(3)
print(np.round(X, 2))

# 리스트 5-1-(4)
print(np.round(T, 2))

# 리스트 5-1-(5)
# 데이터 그래프 ------------------------------
plt.figure(figsize=(4, 4))
plt.plot(X, T, marker='o', linestyle='None',
         markeredgecolor='black', color='cornflowerblue')
plt.xlim(X_min, X_max)
plt.grid(True)
plt.xlabel('Age')
plt.ylabel('Height')
plt.show()

# 리스트 5-1-(6)
from mpl_toolkits.mplot3d import Axes3D
# 평균 오차 함수 ------------------------------
def mse_line(x, t, w): # 나이, 키, (나이 , w[0]), (키 , w[1])
    # x=X ; t=T; w= [x0[i0] , x1[i1]]  ; w[0] = -25.0; w[1]= 120.0
    y = w[0] * x + w[1] # (나이 , w[0]), (키 , w[1])
    mse = np.mean((y - t)**2)
    return mse

# 계산 --------------------------------------
xn = 100 # 등고선 표시 해상도
w0_range = [-25, 25] #나이
w1_range = [120, 170] # 키
x0 = np.linspace(w0_range[0], w0_range[1], xn) #나이
x1 = np.linspace(w1_range[0], w1_range[1], xn) # 키
xx0, xx1 = np.meshgrid(x0, x1)
J = np.zeros((len(x0), len(x1)))
for i0 in range(xn):
    for i1 in range(xn):
        J[i1, i0] = mse_line(X, T, (x0[i0], x1[i1]))
        #  나이, 키, (나이 , w[0]), (키 , w[1])
# 표시 --------------------------------------
plt.figure(figsize=(9.5, 4))
plt.subplots_adjust(wspace=0.5)

ax = plt.subplot(1, 2, 1, projection='3d')
# 오차함수 그리는 부분, 그리드 격자(xx0, xx1) 위에 평균제곱오치를 나타낸는
# 오차함수 J 를 3차원으로 그리는 부분,
# 평면은 나이, 키를 구성하는 가중치값 두 개와 3차원이 되는 z 축은 오차함수 J가 됨
ax.plot_surface(xx0, xx1, J, rstride=10, cstride=10, alpha=0.3,
                color='blue', edgecolor='black')


ax.set_xticks([-20, 0, 20])
ax.set_yticks([120, 140, 160])
ax.view_init(20, -60)

plt.subplot(1, 2, 2)
# 등고선을 나타내는 contour 함수를 사용하여 오차함수를 그려보자
# xx0, xx1의 2차원 평면에 J의 높고 낮음을 등고선 형태로 나타내면,
# 높고 낮음이 있음으로 등고선이 3차원 역할을 함
cont = plt.contour(xx0, xx1, J, 30, colors='black',
                   levels=[100, 1000, 10000, 100000])
# 등고선의 높고 낮음, 높이 차이를 clabel 함수로 나타냄
cont.clabel(fmt='%1.0f', fontsize=8)
plt.grid(True)
plt.show()

# 리스트 5-1-(7)
# 평균 제곱 오차의 기울기 ------------------------

# 머신 규칙(모델링+손실함수, B) 에 대해서 손실함수 해를 경사하강법 (B) 으로 구하기
# 경사하강법 (B) 에 대해 해석해 A를 통해
# 단번에 w* ( 𝑥_𝑘^(new )  ) 를 구하는 것이 아니라,
# 편미분 (𝛻𝑓(𝑥_𝑘 ), 순간변화율, 미분값, 기울기값) 의
# 반복 계산을 통해 해 w* ( 𝑥_𝑘^(new )  ) 를 구한다

def dmse_line(x, t, w): # 나이, 키, (나이 , w[0]), (키 , w[1])
    # w_i[i - 1] = [10, 165]
    # w=[10, 165]
    y = w[0] * x + w[1]
    # array([319.32620059, 354.67245711, 250.09673465, 264.52537227,
    #        415.18614217, 457.06539393, 293.35604454, 388.08065392,
    #        434.09728807, 438.65166588, 236.26105284, 224.76369581,
    #        257.45760489, 434.53562586, 239.58670846, 320.27690625])

    d_w0 = 2 * np.mean((y - t) * x)
    # d_w0 = 4666.79269099332
    d_w1 = 2 * np.mean(y - t)
    # d_w1= 292.60730896834195
    return d_w0, d_w1  # 4666.8  292.6

# 리스트 5-1-(8)
# # 나이 = 10, 키 165, 에서 3차원 오차함수의 기울기 구하기
# 𝛻𝑓(𝑥_𝑘 ) , 순간변화율, 미분값, 기울기값 구하기
d_w = dmse_line(X, T, [10, 165])
print(np.round(d_w, 1))
# [4666.8  292.6]

# 리스트 5-1-(9)
# 경사하강법  ------------------------------------
def fit_line_num(x, t):
    # x=X; t=T
    w_init = [10.0, 165.0] # 초기 매개 변수, 오픈법 시작 지점
    # w_init의 나이 값 10은 원래 나이 데이터 X 에는 없는 값이다
    # w_init의 키 값 165는 원래 키 데이터 T 에는 없는 값이다

    alpha = 0.001 # 학습률
    i_max = 100000 # 반복의 최대 수
    eps = 0.1 # 반복 종료,  기울기의 절대 값의 한계

    w_i = np.zeros([i_max, 2])
    w_i[0, :] = w_init
    # w_i 는 나이 값, 키 값 변화를 담는 그릇
    for i in range(1, i_max):
        dmse = dmse_line(x, t, w_i[i - 1]) # w_i[i - 1] = [10, 165]
        # x=X (나이); t=T (키)
        # 𝛻𝑓(𝑥_𝑘 ) 나이에 대해 경사하강법 적용

        w_i[i, 0] = w_i[i - 1, 0] - alpha * dmse[0]
        # 𝛻𝑓(𝑥_𝑘 ) 나이에 대해 경사하강법 적용
        w_i[i, 1] = w_i[i - 1, 1] - alpha * dmse[1]
        # 𝛻𝑓(𝑥_𝑘 ) 키에 대해 경사하강법 적용
        if max(np.absolute(dmse)) < eps: # 종료판정, np.absolute는 절대치
            print("break i ", i)
            print("break dmse ", dmse)
            # break i  13820
            # break dmse  (-0.005793591015883948, 0.09999091251416559)
            break

    w0 = w_i[i, 0]
    w1 = w_i[i, 1]
    print("w0*, w1* = ", np.round(w_i[i], 2))
    # w0*, w1* =  [  1.54 136.18]
    w_i = w_i[:i, :]

    return w0, w1, dmse, w_i

#  w0, w1, dmse, w_i 확인
# (1.5399473562672923, 136.1761603274906,
#(-0.005793591015883948, 0.09999091251416559),
# array([[ 10.        , 165.        ],
#        [  4.95371356, 164.69820279],
#        [  2.4301957 , 164.54258086],

# 메인 ------------------------------------
plt.figure(figsize=(4, 4)) # MSE의 등고선 표시
xn = 100 # 등고선 해상도
# xn = 1000 # 등고선 해상도
w0_range = [-25, 25]
w1_range = [120, 170]
x0 = np.linspace(w0_range[0], w0_range[1], xn)
x1 = np.linspace(w1_range[0], w1_range[1], xn)
xx0, xx1 = np.meshgrid(x0, x1)
J = np.zeros((len(x0), len(x1)))
for i0 in range(xn):
    for i1 in range(xn):
        J[i1, i0] = mse_line(X, T, (x0[i0], x1[i1]))
cont = plt.contour(xx0, xx1, J, 30, colors='black',
                   levels=(100, 1000, 10000, 100000))
cont.clabel(fmt='%1.0f', fontsize=8) 
plt.grid(True)


# 경사하강법 호출
# 디버깅 포인트
W0, W1, dMSE, W_history = fit_line_num(X, T)
# 결과보기
print('반복 횟수 {0}'.format(W_history.shape[0]))
print('W=[{0:.6f}, {1:.6f}]'.format(W0, W1))
print('dMSE=[{0:.6f}, {1:.6f}]'.format(dMSE[0], dMSE[1]))
print('MSE={0:.6f}'.format(mse_line(X, T, [W0, W1])))

# 디버깅 포인트
plt.plot(W_history[:, 0], W_history[:, 1], '.-',
         color='gray', markersize=10, markeredgecolor='cornflowerblue')
# W_history[0, 0], W_history[0, 1] 부터 먼저 시작
# plt.plot(W_history[0, 0], W_history[0, 1], '.-',
#     ...:          color='gray', markersize=10, markeredgecolor='cornflowerblue')

# np.round([W_history[1, 0], W_history[1, 1]], 2)
# array([  4.95, 164.7 ])
plt.show()

# 리스트 5-1-(10)
# 선 표시 ----------------------------------
def show_line(w):
    xb = np.linspace(X_min, X_max, 100)
    y = w[0] * xb + w[1]
    plt.plot(xb, y, color=(.5, .5, .5), linewidth=4)


# 메인 ------------------------------------
plt.figure(figsize=(4, 4))
W=np.array([W0, W1])
mse = mse_line(X, T, W)
print("w0={0:.3f}, w1={1:.3f}".format(W0, W1))
# mse = mse_line(X, T, W)
print("SD={0:.3f} cm".format(np.sqrt(mse)))
show_line(W) 
plt.plot(X, T, marker='o', linestyle='None',
         color='cornflowerblue', markeredgecolor='black') 
plt.xlim(X_min, X_max)
plt.grid(True)
plt.show()

# W= array([  1.53994736, 136.17616033])

# 리스트 5-1-(11)
# 해석해 ------------------------------------
def fit_line(x, t):
    mx = np.mean(x)
    mt = np.mean(t)
    mtx = np.mean(t * x)
    mxx = np.mean(x * x)
    w0 = (mtx - mt * mx) / (mxx - mx**2)
    w1 = mt - w0 * mx
    return np.array([w0, w1])

# 메인 (기존) ------------------------------------
W = fit_line(X, T)
print("w0={0:.3f}, w1={1:.3f}".format(W[0], W[1]))
mse = mse_line(X, T, W)
print("SD={0:.3f} cm".format(np.sqrt(mse)))
plt.figure(figsize=(4, 4))
show_line(W)
plt.plot(X, T, marker='o', linestyle='None',
         color='cornflowerblue', markeredgecolor='black')
plt.xlim(X_min, X_max)
plt.grid(True)
plt.show()

# 메인 (변경) ------------------------------------
if  __name__ == '__main__':  # 리스트 5-1-(8)
    d_w = dmse_line(X, T, [10, 165])
    print(np.round(d_w, 1))

    # 수치해 메인 ------------------------------------
    plt.figure(figsize=(4, 4))
    W=np.array([W0, W1])
    mse = mse_line(X, T, W)
    print("수치해: w0={0:.3f}, w1={1:.3f}".format(W0, W1))
    # mse = mse_line(X, T, W)
    print("수치해: SD={0:.3f} cm".format(np.sqrt(mse)))
    show_line(W)
    plt.plot(X, T, marker='o', linestyle='None',
             color='cornflowerblue', markeredgecolor='black')
    plt.xlim(X_min, X_max)
    plt.grid(True)
    plt.show()

    # 해석해 메인 ------------------------------------
    W = fit_line(X, T)
    
    # 수치해 W: array([  1.53994736, 136.17616033])
    # 해석해 W: array([  1.55757515, 135.87192426])
    
    print("해석해: w0={0:.3f}, w1={1:.3f}".format(W[0], W[1]))
    mse = mse_line(X, T, W)
    print("해석해: SD={0:.3f} cm".format(np.sqrt(mse)))
    plt.figure(figsize=(4, 4))
    show_line(W)
    plt.plot(X, T, marker='o', linestyle='None',
             color='cornflowerblue', markeredgecolor='black')
    plt.xlim(X_min, X_max)
    plt.grid(True)
    plt.show()


# 리스트 5-1-(12)
# 2차원 데이터 생성 --------------------------
X0 = X
X0_min = 5
X0_max = 30
np.random.seed(seed=1) # 난수를 고정
X1 = 23 * (T / 100)**2 + 2 * np.random.randn(X_n)
X1_min = 40
X1_max = 75

# 리스트 5-1-(13)
print('X0[나이]= ', np.round(X0, 2))
print('X1[몸무게]= ', np.round(X1, 2))
print('T[키]= ', np.round(T, 2))

# 리스트 5-1-(14)
# 2차원 데이터의 표시 ------------------------
def show_data2(ax, x0, x1, t):
    for i in range(len(x0)):
        ax.plot([x0[i], x0[i]], [x1[i], x1[i]],
                [120, t[i]], color='gray')
        # x0[i], x0[i]
        # (15.42555011756435, 15.42555011756435)
        # x1[i], x1[i]
        # (70.43231869836629, 70.43231869836629)
        # 120, t[i]
        # (120, 170.91013144599378)
        ax.plot(x0, x1, t, 'o',
                color='cornflowerblue', markeredgecolor='black',
                markersize=6, markeredgewidth=0.5)
        ax.view_init(elev=35, azim=-75)


# 메인 ------------------------------------
plt.figure(figsize=(6, 5))
ax = plt.subplot(1,1,1,projection='3d')
show_data2(ax, X0, X1, T)
plt.show()

# 리스트 5-1-(15)
#면의 표시 ----------------------------------
def show_plane(ax, w):
    px0 = np.linspace(X0_min, X0_max, 5)
    px1 = np.linspace(X1_min, X1_max, 5)
    px0, px1 = np.meshgrid(px0, px1)
    y = w[0]*px0 + w[1] * px1 + w[2]
    ax.plot_surface(px0, px1, y, rstride=1, cstride=1, alpha=0.3,
                    color='blue', edgecolor='black') 

#면의 MSE -----------------------------------
def mse_plane(x0, x1, t, w):
    y = w[0] * x0 + w[1] * x1 + w[2] # (A)
    mse = np.mean((y - t)**2)
    return mse

# 메인 ------------------------------------
plt.figure(figsize=(6, 5))
ax = plt.subplot(1, 1, 1, projection='3d')
W = [1.5, 1, 90]
show_plane(ax, W) 
show_data2(ax, X0, X1, T)
mse = mse_plane(X0, X1, T, W)
print("SD={0:.3f} cm".format(np.sqrt(mse)))
plt.show()

# 리스트 5-1-(16)
# 해석해 ------------------------------------
def fit_plane(x0, x1, t):
    c_tx0 = np.mean(t * x0) - np.mean(t) * np.mean(x0)
    c_tx1 = np.mean(t * x1) - np.mean(t) * np.mean(x1)
    c_x0x1 = np.mean(x0 * x1) - np.mean(x0) * np.mean(x1)
    v_x0 = np.var(x0)
    v_x1 = np.var(x1)
    w0 = (c_tx1 * c_x0x1 - v_x1 * c_tx0) / (c_x0x1**2 - v_x0 * v_x1)
    w1 = (c_tx0 * c_x0x1 - v_x0 * c_tx1) / (c_x0x1**2 - v_x0 * v_x1)
    w2 = -w0 * np.mean(x0) - w1 * np.mean(x1) + np.mean(t)
    return np.array([w0, w1, w2]) 


# 메인 ------------------------------------
plt.figure(figsize=(6, 5))
ax = plt.subplot(1, 1, 1, projection='3d')
W = fit_plane(X0, X1, T)
print("w0={0:.1f}, w1={1:.1f}, w2={2:.1f}".format(W[0], W[1], W[2]))
show_plane(ax, W)
show_data2(ax, X0, X1, T)
mse = mse_plane(X0, X1, T, W)
print("SD={0:.3f} cm".format(np.sqrt(mse)))
plt.show()

# Commented out IPython magic to ensure Python compatibility.
# --- 리스트 5-2-(1)
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline


# 데이터 로드 ----------------------------
outfile = np.load('ch5_data.npz')
X = outfile['X']
X_min = outfile['X_min']
X_max = outfile['X_max']
X_n = outfile['X_n']
T = outfile['T']

# --- 리스트 5-2-(2)
# 가우스 함수 ---------------------------------
def gauss(x, mu, s):
    return np.exp(-(x - mu)**2 / (2 * s**2))

# 리스트 5-2-(3)
# 메인 ------------------------------------
M = 4
plt.figure(figsize=(4, 4))
mu = np.linspace(5, 30, M)
s = mu[1] - mu[0] # (A)
xb = np.linspace(X_min, X_max, 100)
for j in range(M):
    y = gauss(xb, mu[j], s)
    plt.plot(xb, y, color='gray', linewidth=3)
plt.grid(True)
plt.xlim(X_min, X_max)
plt.ylim(0, 1.2)
plt.show()

# 리스트 5-2-(4)
# 선형 기저 함수 모델 ----------------
def gauss_func(w, x):
    m = len(w) - 1
    mu = np.linspace(5, 30, m)
    s = mu[1] - mu[0]
    y = np.zeros_like(x) # x와 같은 크기로 요소가 0의 행렬 y를 작성
    for j in range(m):
        y = y + w[j] * gauss(x, mu[j], s)
    y = y + w[m]
    return y

# 리스트 5-2-(5)
# 선형 기저 함수 모델 MSE ----------------
def mse_gauss_func(x, t, w):
    y = gauss_func(w, x)
    mse = np.mean((y - t)**2)
    return mse

# 리스트 5-2-(6)
# 선형 기저 함수 모델 정확한 솔루션 -----------------
def fit_gauss_func(x, t, m):
    mu = np.linspace(5, 30, m)
    s = mu[1] - mu[0]
    n = x.shape[0]
    psi = np.ones((n, m+1))
    for j in range(m):
        psi[:, j] = gauss(x, mu[j], s)
    psi_T = np.transpose(psi)
    
    
    b = np.linalg.inv(psi_T.dot(psi))
    c = b.dot(psi_T)
    w = c.dot(t)
    return w

# 리스트 5-2-(7)
# 가우스 기저 함수 표시 -----------------------
def show_gauss_func(w):
    xb = np.linspace(X_min, X_max, 100)
    y = gauss_func(w, xb)
    plt.plot(xb, y, c=[.5, .5, .5], lw=4) 


# 메인 ----------------------------------
plt.figure(figsize=(4, 4))
M = 4
W = fit_gauss_func(X, T, M)
show_gauss_func(W)
plt.plot(X, T, marker='o', linestyle='None',
         color='cornflowerblue', markeredgecolor='black')
plt.xlim(X_min, X_max)
plt.grid(True)
mse = mse_gauss_func(X, T, W)
print('W='+ str(np.round(W,1)))
print("SD={0:.2f} cm".format(np.sqrt(mse)))
plt.show()

# 리스트 5-2-(8)
plt.figure(figsize=(10, 2.5))
plt.subplots_adjust(wspace=0.3)
M = [2, 4, 7, 9]
for i in range(len(M)):
    plt.subplot(1, len(M), i + 1)
    W = fit_gauss_func(X, T, M[i])
    show_gauss_func(W)
    plt.plot(X, T, marker='o', linestyle='None',
             color='cornflowerblue', markeredgecolor='black')
    plt.xlim(X_min, X_max)
    plt.grid(True)
    plt.ylim(130, 180)
    mse = mse_gauss_func(X, T, W)
    
    
    plt.title("M={0:d}, SD={1:.1f}".format(M[i], np.sqrt(mse)))
plt.show()

# 리스트 5-2-(9)
plt.figure(figsize=(5, 4))
M = range(2, 10)
mse2 = np.zeros(len(M))
for i in range(len(M)):
    W = fit_gauss_func(X, T, M[i])
    mse2[i] = np.sqrt(mse_gauss_func(X, T, W))
plt.plot(M, mse2, marker='o',
         color='cornflowerblue', markeredgecolor='black')
plt.grid(True)
plt.show()

# 리스트 5-2-(10)
# 훈련 데이터와 테스트 데이터 ------------------
X_test = X[:int(X_n / 4 + 1)]
T_test = T[:int(X_n / 4 + 1)]
X_train = X[int(X_n / 4 + 1):]
T_train = T[int(X_n / 4 + 1):]
# 메인 ------------------------------------
plt.figure(figsize=(10, 2.5))


plt.subplots_adjust(wspace=0.3)
M = [2, 4, 7, 9]
for i in range(len(M)):
    plt.subplot(1, len(M), i + 1)
    W = fit_gauss_func(X_train, T_train, M[i])
    show_gauss_func(W)
    plt.plot(X_train, T_train, marker='o',
             linestyle='None', color='white',
             markeredgecolor='black', label='training')
    plt.plot(X_test, T_test, marker='o', linestyle='None',
             color='cornflowerblue',
             markeredgecolor='black', label='test')
    plt.legend(loc='lower right', fontsize=10, numpoints=1)
    plt.xlim(X_min, X_max)
    plt.ylim(130, 180)
    plt.grid(True)
    mse = mse_gauss_func(X_test, T_test, W)
    plt.title("M={0:d}, SD={1:.1f}".format(M[i], np.sqrt(mse)))
plt.show()

# 리스트 5-2-(11)
plt.figure(figsize=(5, 4))
M = range(2, 10)
mse_train = np.zeros(len(M))
mse_test = np.zeros(len(M)) 
for i in range(len(M)):
    W = fit_gauss_func(X_train, T_train, M[i])
    mse_train[i] = np.sqrt(mse_gauss_func(X_train, T_train, W))
    mse_test[i] = np.sqrt(mse_gauss_func(X_test, T_test, W))
plt.plot(M, mse_train, marker='o', linestyle='-',
         markerfacecolor='white', markeredgecolor='black',
         color='black', label='training')
plt.plot(M, mse_test, marker='o', linestyle='-',
         color='cornflowerblue', markeredgecolor='black',
         label='test')
plt.legend(loc='upper left', fontsize=10)
plt.ylim(0, 12)
plt.grid(True)
plt.show()

# 리스트 5-2-(12)
# K 분할 교차 검증 -----------------------------
def kfold_gauss_func(x, t, m, k):
    n = x.shape[0]
    mse_train = np.zeros(k)
    mse_test = np.zeros(k)
    for i in range(0, k):
        x_train = x[np.fmod(range(n), k) != i] # (A)
        t_train = t[np.fmod(range(n), k) != i] # (A)
        x_test = x[np.fmod(range(n), k) == i] # (A)
        t_test = t[np.fmod(range(n), k) == i] # (A)
        wm = fit_gauss_func(x_train, t_train, m)
        mse_train[i] = mse_gauss_func(x_train, t_train, wm)
        mse_test[i] = mse_gauss_func(x_test, t_test, wm)
    return mse_train, mse_test

# 리스트 5-2-(13)
np.fmod(range(10),5)

# 리스트 5-2-(14)
M = 4
K = 4
kfold_gauss_func(X, T, M, K)

# 리스트 5-2-(15)
M = range(2, 8)
K = 16
Cv_Gauss_train = np.zeros((K, len(M)))
Cv_Gauss_test = np.zeros((K, len(M)))
for i in range(0, len(M)):
    Cv_Gauss_train[:, i], Cv_Gauss_test[:, i] =\
                    kfold_gauss_func(X, T, M[i], K)
mean_Gauss_train = np.sqrt(np.mean(Cv_Gauss_train, axis=0))
mean_Gauss_test = np.sqrt(np.mean(Cv_Gauss_test, axis=0))


plt.figure(figsize=(4, 3))
plt.plot(M, mean_Gauss_train, marker='o', linestyle='-',
         color='k', markerfacecolor='w', label='training')
plt.plot(M, mean_Gauss_test, marker='o', linestyle='-',
         color='cornflowerblue', markeredgecolor='black', label='test')
plt.legend(loc='upper left', fontsize=10)
plt.ylim(0, 20)
plt.grid(True)
plt.show()

# 리스트 5-2-(16)
M = 3
plt.figure(figsize=(4, 4))
W = fit_gauss_func(X, T, M)
show_gauss_func(W)
plt.plot(X, T, marker='o', linestyle='None',
         color='cornflowerblue', markeredgecolor='black')
plt.xlim([X_min, X_max])
plt.grid(True)
mse = mse_gauss_func(X, T, W)
print("SD={0:.2f} cm".format(np.sqrt(mse)))
plt.show()

# 리스트 5-2-(17)
# 모델 A -----------------------------------
def model_A(x, w):
    y = w[0] - w[1] * np.exp(-w[2] * x)
    return y 


# 모델 A 표시 -------------------------------
def show_model_A(w):
    xb = np.linspace(X_min, X_max, 100)
    y = model_A(xb, w)
    plt.plot(xb, y, c=[.5, .5, .5], lw=4) 


# 모델 A의 MSE ------------------------------
def mse_model_A(w, x, t):
    y = model_A(x, w)
    mse = np.mean((y - t)**2)
    return mse

# 리스트 5-2-(18)
from scipy.optimize import minimize 


# 모델 A의 매개 변수 최적화 -----------------
def fit_model_A(w_init, x, t):
    res1 = minimize(mse_model_A, w_init, args=(x, t), method="powell")
    return res1.x

# 리스트 5-2-(19)
# 메인 ------------------------------------
plt.figure(figsize=(4, 4))
W_init=[100, 0, 0]
W = fit_model_A(W_init, X, T)
print("w0={0:.1f}, w1={1:.1f}, w2={2:.1f}".format(W[0], W[1], W[2]))
show_model_A(W)
plt.plot(X, T, marker='o', linestyle='None',
         color='cornflowerblue',markeredgecolor='black')
plt.xlim(X_min, X_max)
plt.grid(True)
mse = mse_model_A(W, X, T)
print("SD={0:.2f} cm".format(np.sqrt(mse)))
plt.show()

# 리스트 5-2-(20)
# 교차 검증 model_A ---------------------------
def kfold_model_A(x, t, k):
    n = len(x)
    mse_train = np.zeros(k)
    mse_test = np.zeros(k)
    for i in range(0, k):
        x_train = x[np.fmod(range(n), k) != i]
        t_train = t[np.fmod(range(n), k) != i]
        x_test = x[np.fmod(range(n), k) == i]
        t_test = t[np.fmod(range(n), k) == i]
        wm = fit_model_A(np.array([169, 113, 0.2]), x_train, t_train)
        mse_train[i] = mse_model_A(wm, x_train, t_train)
        mse_test[i] = mse_model_A(wm, x_test, t_test)
    return mse_train, mse_test


# 메인 ------------------------------------
K = 16
Cv_A_train, Cv_A_test = kfold_model_A(X, T, K)
mean_A_test = np.sqrt(np.mean(Cv_A_test))
print("Gauss(M=3) SD={0:.2f} cm".format(mean_Gauss_test[1]))
print("Model A SD={0:.2f} cm".format(mean_A_test))
SD = np.append(mean_Gauss_test[0:5], mean_A_test)
M = range(6)
label = ["M=2", "M=3", "M=4", "M=5", "M=6", "Model A"]
plt.figure(figsize=(5, 3))
plt.bar(M, SD, tick_label=label, align="center",
facecolor="cornflowerblue")
plt.show()

